# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='default_compilation_command',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
