# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneide', '0002_auto_20161204_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
