# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneide', '0003_auto_20161204_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='error_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
