# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneide', '0004_auto_20161205_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='output',
            new_name='compilation_output',
        ),
    ]
