# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneide', '0005_auto_20161205_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='error_output',
            new_name='execution_output',
        ),
    ]
