# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneide', '0006_auto_20161205_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='default_exec_ext',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
